#!/bin/sh
# prerm script for multiflexi-pohoda-digest
set -e
. /usr/share/debconf/confmodule
case "$1" in
    remove)
        APPLICATION=`echo $DPKG_MAINTSCRIPT_PACKAGE | sed 's/multiflexi-//'`
        for file in /usr/lib/$APPLICATION/multiflexi/*.json
        do
          [ -e "$file" ] || break
          multiflexi-cli application:remove-json --file "$file"
        done
    ;;

    upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
